[[redirects]]
  from = "/h/:slug/"
  to = "/.netlify/functions/hive-meta?slug=:slug"
  status = 200

[[redirects]]
  from = "/h/:slug"
  to = "/.netlify/functions/hive-meta?slug=:slug"
  status = 200

[[redirects]]
  from = "/api/public-data"
  to = "/.netlify/functions/public-data"
  status = 200

[functions."keep-supabase-awake"]
  schedule = "@daily"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
